services:
  db:
    container_name: symfony-mysql
    environment:
      MYSQL_DATABASE: symfony
      MYSQL_PASSWORD: changeme
      MYSQL_ROOT_PASSWORD: "changeme"
      MYSQL_USER: symfony
    image: mysql:5.7
    ports:
    - 3306:3306/tcp
    volumes:
    - data:/data:rw
version: '3.0'
volumes:
  data: {}
